title: "RotinApp"
description: "Descrição do meu projeto"
url: "https://clcmo.github.io/"
baseurl: "/rotinapp"  # Nome do repositório
theme: "minima"
assets:
  css: "/assets/css"
  js: "/assets/js"

# Ignorar node_modules e pasta de build
exclude:
  - "node_modules"
  - "build"
