name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # Troque para o nome da branch que você usa para desenvolvimento


permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Instalar Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Instalar dependências
          run: npm install

        - name: Fazer o build
          run: npm run  # Altere conforme seu comando de build, ex: npm run build ou yarn build

        - name: Setup Pages
          uses: actions/configure-pages@v5
      
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            # Upload entire repository
            path: '.'

        - name: Instalar Ruby e Bundler
          run: |
              sudo apt-get update
              sudo apt-get install -y ruby-full
              echo 'export GEM_HOME="$HOME/.gem"' >> $GITHUB_ENV
              echo 'export PATH="$HOME/.gem/bin:$PATH"' >> $GITHUB_ENV
              gem install bundler --user-install
    
        - name: Instalar dependências do Jekyll
          run: |
              bundle config set --local path 'vendor/bundle'
              bundle install
          env:
            GEM_HOME: "$HOME/.gem"
            PATH: "$HOME/.gem/bin:$PATH"
    
        - name: Build do site com Jekyll
          run: |
              bundle exec jekyll build --baseurl "/${{ github.event.repository.name }}"
          env:
            GEM_HOME: "$HOME/.gem"
            PATH: "$HOME/.gem/bin:$PATH"
        
        - name: Deploy para GitHub Pages
          uses: JamesIves/github-pages-deploy-action@v4
          with:
              branch: gh-pages
              folder: _site  # Diretório de build do Jekyll
    