name: Deploy com Jekyll e GitHub Pages

on:
  push:
    branches:
      - main  # Branch for deployment

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Ruby com Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false  # Temporarily disable cache to avoid conflicts

      - name: Instalar Jekyll
        run: gem install jekyll

      - name: Instalar dependências do Jekyll
        run: bundle install

      - name: Build do site com Jekyll
        run: bundle exec jekyll build --baseurl "/${{ github.event.repository.name }}"

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site  # Diretório de build do Jekyll
